# Generated by Django 4.2.9 on 2026-03-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'food_categories',
            },
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='foods/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'food_images',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('food_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('vegan', 'Vegan')], default='veg', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('region', models.CharField(choices=[('madhya_pradesh', 'Madhya Pradesh'), ('rajasthan', 'Rajasthan'), ('punjab', 'Punjab'), ('bihar', 'Bihar'), ('uttar_pradesh', 'Uttar Pradesh'), ('gujarat', 'Gujarat'), ('maharashtra', 'Maharashtra'), ('kerala', 'Kerala'), ('tamil_nadu', 'Tamil Nadu'), ('bengal', 'West Bengal'), ('odisha', 'Odisha'), ('karnataka', 'Karnataka'), ('andhra_pradesh', 'Andhra Pradesh'), ('assam', 'Assam'), ('himachal_pradesh', 'Himachal Pradesh'), ('goa', 'Goa'), ('chhattisgarh', 'Chhattisgarh'), ('jharkhand', 'Jharkhand')], max_length=50)),
                ('village_or_city', models.CharField(blank=True, max_length=100)),
                ('cultural_story', models.TextField(help_text='The heritage story behind this dish')),
                ('cooking_method', models.TextField(help_text='Traditional cooking method description')),
                ('ingredients', models.TextField(help_text='List of ingredients, comma separated')),
                ('did_you_know', models.TextField(blank=True, help_text='Interesting fact about this dish')),
                ('grandma_note', models.TextField(blank=True, help_text='A personal touch / grandma tip')),
                ('festival_tag', models.CharField(choices=[('diwali', 'Diwali'), ('holi', 'Holi'), ('pongal', 'Pongal'), ('eid', 'Eid'), ('navratri', 'Navratri'), ('ganesh_chaturthi', 'Ganesh Chaturthi'), ('makar_sankranti', 'Makar Sankranti'), ('baisakhi', 'Baisakhi'), ('onam', 'Onam'), ('durga_puja', 'Durga Puja'), ('none', 'Not Festival Specific')], default='none', max_length=30)),
                ('prep_time_minutes', models.IntegerField(default=30)),
                ('serves', models.IntegerField(default=2)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('total_orders', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='foods.category')),
            ],
            options={
                'db_table': 'food_items',
                'ordering': ['-is_featured', '-total_orders'],
            },
        ),
    ]
