# Generated by Django 4.2.9 on 2026-03-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('story_type', models.CharField(choices=[('food_story', 'Food Story'), ('grandma_recipe', 'Grandma Recipe'), ('village_special', 'Village Special'), ('festival_story', 'Festival Story'), ('chef_story', 'Chef Story')], default='food_story', max_length=20)),
                ('content', models.TextField()),
                ('excerpt', models.CharField(max_length=500)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('video_url', models.URLField(blank=True)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
